2025-01-23 21:08:30.813 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration elegoo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-23 21:08:31.978 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.03 seconds
2025-01-23 21:08:31.978 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.02 seconds
2025-01-23 21:08:31.979 INFO (MainThread) [homeassistant.bootstrap] Setting up frontend: {'frontend'}
2025-01-23 21:08:31.981 INFO (MainThread) [homeassistant.setup] Setting up http
2025-01-23 21:08:31.984 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2025-01-23 21:08:31.984 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.00 seconds
2025-01-23 21:08:31.987 WARNING (MainThread) [aiohttp_fast_zlib] zlib_ng and isal are not available, falling back to zlib, performance will be degraded.
2025-01-23 21:08:31.988 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.01 seconds
2025-01-23 21:08:31.990 INFO (MainThread) [homeassistant.setup] Setting up auth
2025-01-23 21:08:31.990 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.00 seconds
2025-01-23 21:08:31.991 INFO (MainThread) [homeassistant.setup] Setting up config
2025-01-23 21:08:31.992 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.00 seconds
2025-01-23 21:08:31.993 INFO (MainThread) [homeassistant.setup] Setting up diagnostics
2025-01-23 21:08:31.994 INFO (MainThread) [homeassistant.setup] Setup of domain diagnostics took 0.00 seconds
2025-01-23 21:08:31.994 INFO (MainThread) [homeassistant.setup] Setting up file_upload
2025-01-23 21:08:31.995 INFO (MainThread) [homeassistant.setup] Setup of domain file_upload took 0.00 seconds
2025-01-23 21:08:31.995 INFO (MainThread) [homeassistant.setup] Setting up image_upload
2025-01-23 21:08:31.996 INFO (MainThread) [homeassistant.setup] Setup of domain image_upload took 0.00 seconds
2025-01-23 21:08:31.997 INFO (MainThread) [homeassistant.setup] Setting up repairs
2025-01-23 21:08:31.997 INFO (MainThread) [homeassistant.setup] Setup of domain repairs took 0.00 seconds
2025-01-23 21:08:31.998 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2025-01-23 21:08:31.998 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.00 seconds
2025-01-23 21:08:31.998 INFO (MainThread) [homeassistant.setup] Setting up api
2025-01-23 21:08:31.999 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.00 seconds
2025-01-23 21:08:32.000 INFO (MainThread) [homeassistant.setup] Setting up person
2025-01-23 21:08:32.001 INFO (MainThread) [homeassistant.setup] Setting up search
2025-01-23 21:08:32.002 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.00 seconds
2025-01-23 21:08:32.003 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.00 seconds
2025-01-23 21:08:32.003 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2025-01-23 21:08:32.003 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.00 seconds
2025-01-23 21:08:32.004 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2025-01-23 21:08:32.005 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.00 seconds
2025-01-23 21:08:32.006 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of home-assistant-frontend==20250109.0
2025-01-23 21:08:34.942 INFO (MainThread) [homeassistant.setup] Setting up frontend
2025-01-23 21:08:34.944 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.00 seconds
2025-01-23 21:08:34.946 INFO (MainThread) [homeassistant.bootstrap] Setting up recorder: {'recorder'}
2025-01-23 21:08:34.947 INFO (MainThread) [homeassistant.setup] Setting up recorder
2025-01-23 21:08:34.949 INFO (MainThread) [asyncio] <Server sockets=(<asyncio.TransportSocket fd=11, family=2, type=1, proto=6, laddr=('0.0.0.0', 8123)>, <asyncio.TransportSocket fd=12, family=10, type=1, proto=6, laddr=('::', 8123, 0, 0)>)> is serving
2025-01-23 21:08:34.950 INFO (MainThread) [homeassistant.components.http] Now listening on port 8123
2025-01-23 21:08:34.950 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.01 seconds
2025-01-23 21:08:34.951 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //workspaces/elegoo-homeassistant/config/home-assistant_v2.db was shutdown cleanly
2025-01-23 21:08:34.972 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=15 from 2025-01-23 21:02:02.932316)
2025-01-23 21:08:34.979 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.03 seconds
2025-01-23 21:08:34.981 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 1: {'bluetooth', 'http', 'usb', 'repairs', 'network', 'webhook', 'auth', 'websocket_api', 'dhcp', 'api', 'ssdp', 'zeroconf', 'cloud'}
2025-01-23 21:08:34.983 INFO (MainThread) [homeassistant.setup] Setting up network
2025-01-23 21:08:34.984 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of pyudev==0.24.1
2025-01-23 21:08:34.985 INFO (MainThread) [homeassistant.setup] Setup of domain network took 0.00 seconds
2025-01-23 21:08:34.985 INFO (MainThread) [homeassistant.setup] Setting up webhook
2025-01-23 21:08:34.986 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.00 seconds
2025-01-23 21:08:35.110 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of pyserial==3.5
2025-01-23 21:08:35.244 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of zeroconf==0.136.2
2025-01-23 21:08:35.257 INFO (MainThread) [homeassistant.setup] Setting up usb
2025-01-23 21:08:35.258 INFO (MainThread) [homeassistant.setup] Setup of domain usb took 0.00 seconds
2025-01-23 21:08:35.637 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of aiodhcpwatcher==1.0.2
2025-01-23 21:08:35.656 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2025-01-23 21:08:35.658 INFO (MainThread) [homeassistant.components.zeroconf] Starting Zeroconf broadcast
2025-01-23 21:08:35.659 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 0.00 seconds
2025-01-23 21:08:35.882 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of aiodiscover==2.1.0
2025-01-23 21:08:39.201 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of async-upnp-client==0.42.0
2025-01-23 21:08:39.239 INFO (MainThread) [homeassistant.setup] Setting up dhcp
2025-01-23 21:08:39.240 INFO (MainThread) [homeassistant.setup] Setup of domain dhcp took 0.00 seconds
2025-01-23 21:08:39.504 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of pymicro-vad==1.0.1
2025-01-23 21:08:39.549 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2025-01-23 21:08:39.552 INFO (MainThread) [homeassistant.setup] Setup of domain ssdp took 0.00 seconds
2025-01-23 21:08:40.280 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140170241135456] Received unknown command: sensor/numeric_device_classes
2025-01-23 21:08:41.712 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140170236159328] Received unknown command: sensor/numeric_device_classes
2025-01-23 21:08:43.650 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140170236159472] Received unknown command: sensor/numeric_device_classes
2025-01-23 21:08:44.556 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140170236159184] Received unknown command: sensor/numeric_device_classes
2025-01-23 21:08:44.872 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of pyspeex-noise==1.0.2
2025-01-23 21:08:45.471 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140170236160192] Received unknown command: sensor/numeric_device_classes
2025-01-23 21:08:46.308 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140170236160912] Received unknown command: sensor/numeric_device_classes
2025-01-23 21:08:49.128 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140170236161200] Received unknown command: sensor/numeric_device_classes
2025-01-23 21:08:50.406 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of bleak-retry-connector==3.6.0
2025-01-23 21:08:50.816 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of bluetooth-data-tools==1.20.0
2025-01-23 21:08:51.060 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of habluetooth==3.7.0
2025-01-23 21:08:51.696 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of mutagen==1.47.0
2025-01-23 21:08:51.739 INFO (MainThread) [homeassistant.setup] Setting up bluetooth
2025-01-23 21:08:51.752 INFO (MainThread) [homeassistant.setup] Setup of domain bluetooth took 0.01 seconds
2025-01-23 21:08:51.946 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of ha-ffmpeg==3.2.2
2025-01-23 21:08:52.073 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of hassil==2.1.0
2025-01-23 21:08:52.245 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of home-assistant-intents==2025.1.1
2025-01-23 21:08:52.394 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of python-matter-server==6.6.0
2025-01-23 21:08:52.648 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of PyTurboJPEG==1.7.5
2025-01-23 21:08:53.387 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140170223786672] Received unknown command: sensor/numeric_device_classes
2025-01-23 21:08:53.548 INFO (MainThread) [homeassistant.setup] Setting up cloud
2025-01-23 21:08:53.551 INFO (MainThread) [homeassistant.setup] Setting up ffmpeg
2025-01-23 21:08:53.553 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.00 seconds
2025-01-23 21:08:53.556 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'person', 'default_config', 'radio_browser', 'conversation', 'elegoo', 'scene', 'diagnostics', 'application_credentials', 'input_select', 'stt', 'blueprint', 'google_translate', 'shopping_list', 'onboarding', 'input_text', 'input_number', 'energy', 'automation', 'stream', 'config', 'assist_pipeline', 'hardware', 'input_button', 'history', 'intent', 'media_source', 'tts', 'backup', 'input_datetime', 'logbook', 'my', 'ffmpeg', 'lovelace', 'search', 'mobile_app', 'homeassistant_alerts', 'zone', 'system_health', 'script', 'image_upload', 'schedule', 'file_upload', 'timer', 'tag', 'analytics', 'counter', 'sun', 'input_boolean', 'device_automation', 'camera', 'go2rtc', 'trace', 'wake_word'}
2025-01-23 21:08:53.558 INFO (MainThread) [homeassistant.setup] Setting up scene
2025-01-23 21:08:53.561 INFO (MainThread) [homeassistant.components.scene] Setting up homeassistant.scene
2025-01-23 21:08:53.562 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 0.00 seconds
2025-01-23 21:08:53.563 INFO (MainThread) [homeassistant.setup] Setting up stt
2025-01-23 21:08:53.564 INFO (MainThread) [homeassistant.setup] Setup of domain stt took 0.00 seconds
2025-01-23 21:08:53.564 INFO (MainThread) [homeassistant.setup] Setting up wake_word
2025-01-23 21:08:53.564 INFO (MainThread) [homeassistant.setup] Setup of domain wake_word took 0.00 seconds
2025-01-23 21:08:53.565 INFO (MainThread) [homeassistant.setup] Setting up camera
2025-01-23 21:08:53.566 INFO (MainThread) [homeassistant.setup] Setup of domain camera took 0.00 seconds
2025-01-23 21:08:53.568 INFO (MainThread) [homeassistant.setup] Setting up history
2025-01-23 21:08:53.568 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.00 seconds
2025-01-23 21:08:53.572 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of go2rtc-client==0.1.2
2025-01-23 21:08:53.578 INFO (MainThread) [homeassistant.setup] Setting up logbook
2025-01-23 21:08:53.581 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.00 seconds
2025-01-23 21:08:53.581 INFO (MainThread) [homeassistant.setup] Setting up media_source
2025-01-23 21:08:53.583 INFO (MainThread) [homeassistant.setup] Setup of domain media_source took 0.00 seconds
2025-01-23 21:08:53.593 INFO (MainThread) [homeassistant.setup] Setting up input_select
2025-01-23 21:08:53.595 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 0.00 seconds
2025-01-23 21:08:53.596 INFO (MainThread) [homeassistant.setup] Setting up zone
2025-01-23 21:08:53.602 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.01 seconds
2025-01-23 21:08:53.607 INFO (MainThread) [homeassistant.setup] Setting up system_health
2025-01-23 21:08:53.610 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.00 seconds
2025-01-23 21:08:53.612 INFO (MainThread) [homeassistant.setup] Setting up blueprint
2025-01-23 21:08:53.613 INFO (MainThread) [homeassistant.setup] Setup of domain blueprint took 0.00 seconds
2025-01-23 21:08:53.614 INFO (MainThread) [homeassistant.setup] Setting up trace
2025-01-23 21:08:53.615 INFO (MainThread) [homeassistant.setup] Setup of domain trace took 0.00 seconds
2025-01-23 21:08:53.616 INFO (MainThread) [homeassistant.setup] Setting up script
2025-01-23 21:08:53.623 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.01 seconds
2025-01-23 21:08:53.638 INFO (MainThread) [homeassistant.setup] Setting up input_number
2025-01-23 21:08:53.642 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 0.00 seconds
2025-01-23 21:08:53.643 INFO (MainThread) [homeassistant.setup] Setting up timer
2025-01-23 21:08:53.645 INFO (MainThread) [homeassistant.setup] Setup of domain timer took 0.00 seconds
2025-01-23 21:08:53.646 INFO (MainThread) [homeassistant.setup] Setting up automation
2025-01-23 21:08:53.647 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.00 seconds
2025-01-23 21:08:53.650 INFO (MainThread) [homeassistant.setup] Setting up input_button
2025-01-23 21:08:53.652 INFO (MainThread) [homeassistant.setup] Setup of domain input_button took 0.00 seconds
2025-01-23 21:08:53.656 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2025-01-23 21:08:53.657 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 0.00 seconds
2025-01-23 21:08:53.657 INFO (MainThread) [homeassistant.setup] Setting up backup
2025-01-23 21:08:53.659 INFO (MainThread) [homeassistant.setup] Setup of domain backup took 0.00 seconds
2025-01-23 21:08:53.662 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-1' coro=<setup_and_run_hass() running at /home/vscode/.local/lib/python3.13/site-packages/homeassistant/runner.py:122> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.13/asyncio/tasks.py:765> cb=[_run_until_complete_cb() at /usr/local/lib/python3.13/asyncio/base_events.py:181] created at /usr/local/lib/python3.13/asyncio/tasks.py:748> took 0.108 seconds
2025-01-23 21:08:53.664 INFO (MainThread) [homeassistant.setup] Setting up intent
2025-01-23 21:08:53.665 INFO (MainThread) [homeassistant.setup] Setup of domain intent took 0.00 seconds
2025-01-23 21:08:53.665 INFO (MainThread) [homeassistant.setup] Setting up energy
2025-01-23 21:08:53.666 INFO (MainThread) [homeassistant.setup] Setting up sensor
2025-01-23 21:08:53.667 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.00 seconds
2025-01-23 21:08:53.668 INFO (MainThread) [homeassistant.setup] Setup of domain energy took 0.00 seconds
2025-01-23 21:08:53.669 INFO (MainThread) [homeassistant.setup] Setting up homeassistant_alerts
2025-01-23 21:08:53.669 INFO (MainThread) [homeassistant.setup] Setup of domain homeassistant_alerts took 0.00 seconds
2025-01-23 21:08:53.670 INFO (MainThread) [homeassistant.setup] Setting up tag
2025-01-23 21:08:53.671 INFO (MainThread) [homeassistant.setup] Setup of domain tag took 0.00 seconds
2025-01-23 21:08:53.671 INFO (MainThread) [homeassistant.setup] Setting up my
2025-01-23 21:08:53.672 INFO (MainThread) [homeassistant.setup] Setup of domain my took 0.00 seconds
2025-01-23 21:08:53.672 INFO (MainThread) [homeassistant.setup] Setting up sun
2025-01-23 21:08:53.673 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.00 seconds
2025-01-23 21:08:53.675 INFO (MainThread) [homeassistant.components.sensor] Setting up sun.sensor
2025-01-23 21:08:53.677 INFO (MainThread) [homeassistant.setup] Setting up elegoo
2025-01-23 21:08:53.677 INFO (MainThread) [custom_components.elegoo_ha] Elegoo Home Assistant Add-on is starting
2025-01-23 21:08:54.690 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'elegoo_ha' accesses hass.helpers.event, which should be updated to import functions used from event directly at custom_components/elegoo_ha/__init__.py, line 76: hass.helpers.event.async_track_time_interval(. This will stop working in Home Assistant 2025.5, please report it to the author of the 'elegoo_ha' custom integration
2025-01-23 21:08:54.690 ERROR (MainThread) [homeassistant.setup] Error during setup of component elegoo
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/workspaces/elegoo-homeassistant/custom_components/elegoo_ha/__init__.py", line 77, in async_setup
    elegoo_printer.get_printer_status(), datetime.timedelta(seconds=30)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/workspaces/elegoo-homeassistant/custom_components/elegoo_ha/printer.py", line 38, in get_printer_status
    self._send_printer_cmd(0)
    ~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/workspaces/elegoo-homeassistant/custom_components/elegoo_ha/printer.py", line 58, in _send_printer_cmd
    self.printer_websocket.send(json.dumps(payload))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/websocket/_app.py", line 290, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
                        ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/websocket/_core.py", line 297, in send
    return self.send_frame(frame)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/websocket/_core.py", line 337, in send_frame
    l = self._send(data)
  File "/home/vscode/.local/lib/python3.13/site-packages/websocket/_core.py", line 559, in _send
    return send(self.sock, data)
  File "/home/vscode/.local/lib/python3.13/site-packages/websocket/_socket.py", line 152, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
2025-01-23 21:08:54.692 INFO (MainThread) [homeassistant.setup] Setup of domain elegoo took 1.01 seconds
2025-01-23 21:08:54.692 WARNING (MainThread) [asyncio] Executing <Task finished name='setup component elegoo' coro=<async_setup_component() done, defined at /home/vscode/.local/lib/python3.13/site-packages/homeassistant/setup.py:145> result=False created at /home/vscode/.local/lib/python3.13/site-packages/homeassistant/util/async_.py:45> took 1.015 seconds
2025-01-23 21:08:54.692 INFO (MainThread) [homeassistant.setup] Setting up application_credentials
2025-01-23 21:08:54.693 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 0.00 seconds
2025-01-23 21:08:54.695 INFO (MainThread) [homeassistant.setup] Setting up schedule
2025-01-23 21:08:54.696 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 0.00 seconds
2025-01-23 21:08:54.697 INFO (MainThread) [homeassistant.setup] Setting up shopping_list
2025-01-23 21:08:54.697 INFO (MainThread) [homeassistant.setup] Setup of domain shopping_list took 0.00 seconds
2025-01-23 21:08:54.698 INFO (MainThread) [homeassistant.setup] Setting up input_text
2025-01-23 21:08:54.699 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 0.00 seconds
2025-01-23 21:08:54.700 INFO (MainThread) [homeassistant.setup] Setting up hardware
2025-01-23 21:08:54.700 INFO (MainThread) [homeassistant.setup] Setting up counter
2025-01-23 21:08:54.702 INFO (MainThread) [homeassistant.setup] Setup of domain counter took 0.00 seconds
2025-01-23 21:08:54.703 INFO (MainThread) [homeassistant.setup] Setting up input_datetime
2025-01-23 21:08:54.705 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 0.00 seconds
2025-01-23 21:08:54.717 INFO (MainThread) [asyncio] <_UnixWritePipeTransport fd=22 idle bufsize=0> was closed by peer
2025-01-23 21:08:54.720 INFO (MainThread) [asyncio] execute program 'ffmpeg': <_UnixSubprocessTransport pid=2592 running stdin=<_UnixWritePipeTransport closing fd=22 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=23 polling>>
2025-01-23 21:08:54.722 INFO (Thread-2 (<lambda>)) [websocket] Websocket connected
2025-01-23 21:08:54.722 INFO (MainThread) [homeassistant.setup] Setting up conversation
2025-01-23 21:08:54.723 INFO (MainThread) [homeassistant.setup] Setup of domain conversation took 0.00 seconds
2025-01-23 21:08:54.724 INFO (MainThread) [homeassistant.components.sensor] Setting up energy.sensor
2025-01-23 21:08:54.729 INFO (MainThread) [asyncio] <_UnixSubprocessTransport pid=2592 running stdin=<_UnixWritePipeTransport closed fd=22 closed> stdout=<_UnixReadPipeTransport fd=23 polling>> exited with return code 0
2025-01-23 21:08:54.734 INFO (MainThread) [asyncio] <_UnixReadPipeTransport fd=23 polling> was closed by peer
2025-01-23 21:08:54.745 INFO (MainThread) [homeassistant.setup] Setup of domain hardware took 0.05 seconds
2025-01-23 21:08:54.756 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of av==13.1.0
2025-01-23 21:08:54.762 INFO (MainThread) [homeassistant.setup] Setting up analytics
2025-01-23 21:08:54.766 INFO (MainThread) [homeassistant.setup] Setup of domain analytics took 0.00 seconds
2025-01-23 21:08:54.771 INFO (MainThread) [homeassistant.setup] Setting up go2rtc
2025-01-23 21:08:54.772 INFO (MainThread) [homeassistant.setup] Setting up todo
2025-01-23 21:08:54.773 INFO (MainThread) [homeassistant.setup] Setup of domain todo took 0.00 seconds
2025-01-23 21:08:54.774 INFO (MainThread) [homeassistant.components.todo] Setting up shopping_list.todo
2025-01-23 21:08:54.776 INFO (MainThread) [homeassistant.setup] Setup of domain ffmpeg took 1.22 seconds
2025-01-23 21:08:54.776 ERROR (MainThread) [homeassistant.components.go2rtc] Could not find go2rtc docker binary
2025-01-23 21:08:54.776 ERROR (MainThread) [homeassistant.setup] Setup failed for 'go2rtc': Integration failed to initialize.
2025-01-23 21:08:54.776 INFO (MainThread) [homeassistant.setup] Setup of domain go2rtc took 0.01 seconds
2025-01-23 21:08:54.777 INFO (MainThread) [homeassistant.setup] Setting up tts
2025-01-23 21:08:54.780 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.00 seconds
2025-01-23 21:08:54.782 INFO (MainThread) [homeassistant.setup] Setting up assist_pipeline
2025-01-23 21:08:54.783 INFO (MainThread) [homeassistant.setup] Setup of domain assist_pipeline took 0.00 seconds
2025-01-23 21:08:55.457 INFO (MainThread) [homeassistant.setup] Setting up stream
2025-01-23 21:08:55.458 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of radios==0.3.2
2025-01-23 21:08:55.485 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.03 seconds
2025-01-23 21:08:56.141 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of gTTS==2.2.4
2025-01-23 21:08:56.175 INFO (MainThread) [homeassistant.setup] Setting up radio_browser
2025-01-23 21:08:56.175 INFO (MainThread) [homeassistant.setup] Setup of domain radio_browser took 0.00 seconds
2025-01-23 21:08:57.517 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of PyNaCl==1.5.0
2025-01-23 21:08:57.520 INFO (MainThread) [homeassistant.setup] Setting up google_translate
2025-01-23 21:08:57.520 INFO (MainThread) [homeassistant.setup] Setup of domain google_translate took 0.00 seconds
2025-01-23 21:08:57.529 INFO (MainThread) [homeassistant.components.tts] Setting up google_translate.tts
2025-01-23 21:08:57.721 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2025-01-23 21:08:57.722 INFO (MainThread) [homeassistant.setup] Setting up notify
2025-01-23 21:08:57.724 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.00 seconds
2025-01-23 21:08:57.724 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.00 seconds
2025-01-23 21:08:57.725 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2025-01-23 21:08:57.726 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'default_config'. Setup failed for dependencies: ['go2rtc']
2025-01-23 21:08:57.726 ERROR (MainThread) [homeassistant.setup] Setup failed for 'default_config': Could not setup dependencies: go2rtc
2025-01-23 21:08:57.728 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 26.92s
2025-01-23 21:08:57.728 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2025-01-23 21:08:57.788 WARNING (Thread-2 (<lambda>)) [homeassistant.helpers.entity] Entity sensor.elegoo_printer_uvled_temperature (<class 'custom_components.elegoo_ha.models.PrinterSensor'>) is using self.async_update_ha_state(), without enabling force_refresh. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
2025-01-23 21:08:57.788 WARNING (Thread-2 (<lambda>)) [homeassistant.helpers.entity] Entity sensor.elegoo_printer_time_total (<class 'custom_components.elegoo_ha.models.PrinterSensor'>) is using self.async_update_ha_state(), without enabling force_refresh. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
2025-01-23 21:08:57.788 WARNING (Thread-2 (<lambda>)) [homeassistant.helpers.entity] Entity sensor.elegoo_printer_time_printing (<class 'custom_components.elegoo_ha.models.PrinterSensor'>) is using self.async_update_ha_state(), without enabling force_refresh. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
2025-01-23 21:08:57.788 WARNING (Thread-2 (<lambda>)) [homeassistant.helpers.entity] Entity sensor.elegoo_printer_time_remaining (<class 'custom_components.elegoo_ha.models.PrinterSensor'>) is using self.async_update_ha_state(), without enabling force_refresh. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
2025-01-23 21:08:57.788 WARNING (Thread-2 (<lambda>)) [homeassistant.helpers.entity] Entity sensor.elegoo_printer_filename (<class 'custom_components.elegoo_ha.models.PrinterSensor'>) is using self.async_update_ha_state(), without enabling force_refresh. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
2025-01-23 21:08:57.788 WARNING (Thread-2 (<lambda>)) [homeassistant.helpers.entity] Entity sensor.elegoo_printer_current_layer (<class 'custom_components.elegoo_ha.models.PrinterSensor'>) is using self.async_update_ha_state(), without enabling force_refresh. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
2025-01-23 21:08:57.788 WARNING (Thread-2 (<lambda>)) [homeassistant.helpers.entity] Entity sensor.elegoo_printer_total_layers (<class 'custom_components.elegoo_ha.models.PrinterSensor'>) is using self.async_update_ha_state(), without enabling force_refresh. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
2025-01-23 21:08:57.788 WARNING (Thread-2 (<lambda>)) [homeassistant.helpers.entity] Entity sensor.elegoo_printer_remaining_layers (<class 'custom_components.elegoo_ha.models.PrinterSensor'>) is using self.async_update_ha_state(), without enabling force_refresh. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
2025-01-23 21:08:57.841 INFO (MainThread) [asyncio] <Server sockets=(<asyncio.TransportSocket fd=26, family=2, type=1, proto=6, laddr=('172.17.0.2', 40000)>,)> is serving
2025-01-23 21:08:57.960 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-147' coro=<async_setup.<locals>.initial_refresh() running at /home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/homeassistant_alerts/__init__.py:102> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.13/asyncio/base_events.py:459> cb=[set.remove()] created at /home/vscode/.local/lib/python3.13/site-packages/homeassistant/util/async_.py:45> took 0.102 seconds
2025-01-23 21:08:59.782 ERROR (Thread-2 (<lambda>)) [homeassistant.core] Error running job: <Job listen state_changed HassJobType.Callback functools.partial(<function _forward_entity_changes at 0x7f7bf8b31120>, <bound method WebSocketHandler._send_message of <WebSocketHandler closing=False authenticated=True description=daniel from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36)>>, None, None, User(name='daniel', perm_lookup=PermissionLookup(entity_registry=<homeassistant.helpers.entity_registry.EntityRegistry object at 0x7f7bf879b0e0>, device_registry=<homeassistant.helpers.device_registry.DeviceRegistry object at 0x7f7bf879ae40>), id='9eea722936ce4417b0c3c283b18d26fd', is_owner=True, is_active=True, system_generated=False, local_only=False, groups=[Group(name='Administrators', policy={'entities': True}, id='system-admin', system_generated=True)], credentials=[Credentials(auth_provider_type='homeassistant', auth_provider_id=None, data={'username': 'daniel'}, id='291135a7d46c4a2c872c8e4443cdbe89', is_new=False)], refresh_tokens={'5683520a6e874505868b94b0862b7e09': RefreshToken(user=..., client_id='http://localhost:8123/', access_token_expiration=datetime.timedelta(seconds=1800), client_name=None, client_icon=None, token_type='normal', id='5683520a6e874505868b94b0862b7e09', created_at=datetime.datetime(2025, 1, 23, 19, 15, 30, 18846, tzinfo=datetime.timezone.utc), token='12d540764c84e20ea8c78114c9a863d1ab1f099cab421dc955f7fea5e4aeb93be9a1fa13c5208850b3002409d8e4a45c8bf5fc50301d64dd4ff00a5c2cd19253', jwt_key='a05c00dbbeb31aafcb1a9246ca45dadffd0cfa4acf8433457e3b208fd793bcda39a02e136f70e80b1ea6dd415ab263853dc5318d173091de18f9b9b4202581e4', last_used_at=datetime.datetime(2025, 1, 23, 19, 15, 30, 18960, tzinfo=datetime.timezone.utc), last_used_ip='127.0.0.1', expire_at=1745435730.01896, credential=Credentials(auth_provider_type='homeassistant', auth_provider_id=None, data={'username': 'daniel'}, id='291135a7d46c4a2c872c8e4443cdbe89', is_new=False), version='2025.1.3'), '80e618a7a0374c89affd5b081025e036': RefreshToken(user=..., client_id='http://localhost:8123/', access_token_expiration=datetime.timedelta(seconds=1800), client_name=None, client_icon=None, token_type='normal', id='80e618a7a0374c89affd5b081025e036', created_at=datetime.datetime(2025, 1, 23, 19, 17, 50, 616730, tzinfo=datetime.timezone.utc), token='064062a28524291261d2b819747250cf0ddbef0afcf95b55a1fb54c6193b23c1f5071fea51f2d7a5e84cc1dc93495784ae51477fbb343bd59098ecb9234fcef4', jwt_key='e3790abcdb20c960d2f9c8cf307a18c451625ea58044f489fe63170e152f81c0de12d1cd828cbfb85de653fd9ac3630816bf5c7781047ebf61253c683b4c4799', last_used_at=datetime.datetime(2025, 1, 23, 19, 17, 50, 616857, tzinfo=datetime.timezone.utc), last_used_ip='127.0.0.1', expire_at=1745435870.616857, credential=Credentials(auth_provider_type='homeassistant', auth_provider_id=None, data={'username': 'daniel'}, id='291135a7d46c4a2c872c8e4443cdbe89', is_new=False), version='2025.1.3'), '606b6fda179647829f56bc0ec59ed155': RefreshToken(user=..., client_id='http://localhost:8123/', access_token_expiration=datetime.timedelta(seconds=1800), client_name=None, client_icon=None, token_type='normal', id='606b6fda179647829f56bc0ec59ed155', created_at=datetime.datetime(2025, 1, 23, 20, 35, 52, 741286, tzinfo=datetime.timezone.utc), token='16cbd8253f9f4322f87ba2d531ad4eda4d0ff1497c2226851dc7c514e4ba67f4efeaf182289f60c5070a37963b6e285d2862bf37eda9373e1ffb58cb188a5f11', jwt_key='1534e24cc1ef5dc001d9f4fcc9d02e0a81c745a3b6adeeed60d3621b10f3fe2919f7d6e5ff4d461853ac516d3ea00e9501d1ccc7aef51f2b1ca73b11263ff678', last_used_at=datetime.datetime(2025, 1, 23, 21, 8, 39, 845098, tzinfo=datetime.timezone.utc), last_used_ip='127.0.0.1', expire_at=1745442519.845098, credential=Credentials(auth_provider_type='homeassistant', auth_provider_id=None, data={'username': 'daniel'}, id='291135a7d46c4a2c872c8e4443cdbe89', is_new=False), version='2025.1.3')}), b'3')>
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/core.py", line 1578, in async_fire_internal
    self._hass.async_run_hass_job(job, event)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 394, in _forward_entity_changes
    send_message(messages.cached_state_diff_message(message_id_as_bytes, event))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/http.py", line 225, in _send_message
    self._loop.call_soon(self._release_ready_future_or_reschedule)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 830, in call_soon
    self._check_thread()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 867, in _check_thread
    raise RuntimeError(
        "Non-thread-safe operation invoked on an event loop other "
        "than the current one")
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
2025-01-23 21:09:05.877 ERROR (Thread-2 (<lambda>)) [homeassistant.core] Error running job: <Job listen state_changed HassJobType.Callback functools.partial(<function _forward_entity_changes at 0x7f7bf8b31120>, <bound method WebSocketHandler._send_message of <WebSocketHandler closing=False authenticated=True description=daniel from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36)>>, None, None, User(name='daniel', perm_lookup=PermissionLookup(entity_registry=<homeassistant.helpers.entity_registry.EntityRegistry object at 0x7f7bf879b0e0>, device_registry=<homeassistant.helpers.device_registry.DeviceRegistry object at 0x7f7bf879ae40>), id='9eea722936ce4417b0c3c283b18d26fd', is_owner=True, is_active=True, system_generated=False, local_only=False, groups=[Group(name='Administrators', policy={'entities': True}, id='system-admin', system_generated=True)], credentials=[Credentials(auth_provider_type='homeassistant', auth_provider_id=None, data={'username': 'daniel'}, id='291135a7d46c4a2c872c8e4443cdbe89', is_new=False)], refresh_tokens={'5683520a6e874505868b94b0862b7e09': RefreshToken(user=..., client_id='http://localhost:8123/', access_token_expiration=datetime.timedelta(seconds=1800), client_name=None, client_icon=None, token_type='normal', id='5683520a6e874505868b94b0862b7e09', created_at=datetime.datetime(2025, 1, 23, 19, 15, 30, 18846, tzinfo=datetime.timezone.utc), token='12d540764c84e20ea8c78114c9a863d1ab1f099cab421dc955f7fea5e4aeb93be9a1fa13c5208850b3002409d8e4a45c8bf5fc50301d64dd4ff00a5c2cd19253', jwt_key='a05c00dbbeb31aafcb1a9246ca45dadffd0cfa4acf8433457e3b208fd793bcda39a02e136f70e80b1ea6dd415ab263853dc5318d173091de18f9b9b4202581e4', last_used_at=datetime.datetime(2025, 1, 23, 19, 15, 30, 18960, tzinfo=datetime.timezone.utc), last_used_ip='127.0.0.1', expire_at=1745435730.01896, credential=Credentials(auth_provider_type='homeassistant', auth_provider_id=None, data={'username': 'daniel'}, id='291135a7d46c4a2c872c8e4443cdbe89', is_new=False), version='2025.1.3'), '80e618a7a0374c89affd5b081025e036': RefreshToken(user=..., client_id='http://localhost:8123/', access_token_expiration=datetime.timedelta(seconds=1800), client_name=None, client_icon=None, token_type='normal', id='80e618a7a0374c89affd5b081025e036', created_at=datetime.datetime(2025, 1, 23, 19, 17, 50, 616730, tzinfo=datetime.timezone.utc), token='064062a28524291261d2b819747250cf0ddbef0afcf95b55a1fb54c6193b23c1f5071fea51f2d7a5e84cc1dc93495784ae51477fbb343bd59098ecb9234fcef4', jwt_key='e3790abcdb20c960d2f9c8cf307a18c451625ea58044f489fe63170e152f81c0de12d1cd828cbfb85de653fd9ac3630816bf5c7781047ebf61253c683b4c4799', last_used_at=datetime.datetime(2025, 1, 23, 19, 17, 50, 616857, tzinfo=datetime.timezone.utc), last_used_ip='127.0.0.1', expire_at=1745435870.616857, credential=Credentials(auth_provider_type='homeassistant', auth_provider_id=None, data={'username': 'daniel'}, id='291135a7d46c4a2c872c8e4443cdbe89', is_new=False), version='2025.1.3'), '606b6fda179647829f56bc0ec59ed155': RefreshToken(user=..., client_id='http://localhost:8123/', access_token_expiration=datetime.timedelta(seconds=1800), client_name=None, client_icon=None, token_type='normal', id='606b6fda179647829f56bc0ec59ed155', created_at=datetime.datetime(2025, 1, 23, 20, 35, 52, 741286, tzinfo=datetime.timezone.utc), token='16cbd8253f9f4322f87ba2d531ad4eda4d0ff1497c2226851dc7c514e4ba67f4efeaf182289f60c5070a37963b6e285d2862bf37eda9373e1ffb58cb188a5f11', jwt_key='1534e24cc1ef5dc001d9f4fcc9d02e0a81c745a3b6adeeed60d3621b10f3fe2919f7d6e5ff4d461853ac516d3ea00e9501d1ccc7aef51f2b1ca73b11263ff678', last_used_at=datetime.datetime(2025, 1, 23, 21, 8, 39, 845098, tzinfo=datetime.timezone.utc), last_used_ip='127.0.0.1', expire_at=1745442519.845098, credential=Credentials(auth_provider_type='homeassistant', auth_provider_id=None, data={'username': 'daniel'}, id='291135a7d46c4a2c872c8e4443cdbe89', is_new=False), version='2025.1.3')}), b'3')>
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/core.py", line 1578, in async_fire_internal
    self._hass.async_run_hass_job(job, event)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 394, in _forward_entity_changes
    send_message(messages.cached_state_diff_message(message_id_as_bytes, event))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/http.py", line 225, in _send_message
    self._loop.call_soon(self._release_ready_future_or_reschedule)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 830, in call_soon
    self._check_thread()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 867, in _check_thread
    raise RuntimeError(
        "Non-thread-safe operation invoked on an event loop other "
        "than the current one")
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
2025-01-23 21:09:11.953 ERROR (MainThread) [homeassistant] Error doing job: unhandled exception during shutdown (<Task finished name='Task-177' coro=<RequestHandler._handle_request() done, defined at /home/vscode/.local/lib/python3.13/site-packages/aiohttp/web_protocol.py:470> exception=InvalidStateError('invalid state') created at /home/vscode/.local/lib/python3.13/site-packages/aiohttp/web_protocol.py:559>)
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/http.py", line 343, in async_handle
    await self._async_websocket_command_phase(connection)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/http.py", line 463, in _async_websocket_command_phase
    msg = await wsock.receive()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/aiohttp/web_ws.py", line 536, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_websocket/reader_c.py", line 112, in read
  File "aiohttp/_websocket/reader_c.py", line 109, in aiohttp._websocket.reader_c.WebSocketDataQueue.read
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/http.py", line 57, in get
    return await WebSocketHandler(request.app[KEY_HASS], request).async_handle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/http.py", line 368, in async_handle
    await self._async_cleanup_writer_and_close(disconnect_warn, connection)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/http.py", line 516, in _async_cleanup_writer_and_close
    await wsock.close()
  File "/home/vscode/.local/lib/python3.13/site-packages/aiohttp/web_ws.py", line 480, in close
    msg = await reader.read()
          ^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_websocket/reader_c.py", line 112, in read
  File "aiohttp/_websocket/reader_c.py", line 109, in aiohttp._websocket.reader_c.WebSocketDataQueue.read
asyncio.exceptions.CancelledError: Final process shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 509, in _handle_request
    self._handler_waiter.set_result(None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
asyncio.exceptions.InvalidStateError: invalid state
2025-01-23 21:09:11.956 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/home/vscode/.local/bin/hass", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1995, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.13/selectors.py", line 452, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
